//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID { get; set; }
        public int SamsatID { get; set; }
        public int JenisUser { get; set; }
        public string Nama { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Samsat Samsat { get; set; }
    }
}
