//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIPEntities : DbContext
    {
        public SIPEntities()
            : base("name=SIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BahanBakar> BahanBakar { get; set; }
        public virtual DbSet<DetailTagihan> DetailTagihan { get; set; }
        public virtual DbSet<JenisKendaraan> JenisKendaraan { get; set; }
        public virtual DbSet<JenisTagihan> JenisTagihan { get; set; }
        public virtual DbSet<Kendaraan> Kendaraan { get; set; }
        public virtual DbSet<Kota> Kota { get; set; }
        public virtual DbSet<Merek> Merek { get; set; }
        public virtual DbSet<PemilikKendaraan> PemilikKendaraan { get; set; }
        public virtual DbSet<Provinsi> Provinsi { get; set; }
        public virtual DbSet<Samsat> Samsat { get; set; }
        public virtual DbSet<Tagihan> Tagihan { get; set; }
        public virtual DbSet<Warna> Warna { get; set; }
    }
}
