//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTagihan
    {
        public int TagihanID { get; set; }
        public int JenisTagihanID { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public Nullable<int> Denda { get; set; }
    
        public virtual JenisTagihan JenisTagihan { get; set; }
        public virtual Tagihan Tagihan { get; set; }
    }
}
