//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JenisTagihan
    {
        public JenisTagihan()
        {
            this.DetailTagihan = new HashSet<DetailTagihan>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public Nullable<double> PersenDenda { get; set; }
    
        public virtual ICollection<DetailTagihan> DetailTagihan { get; set; }
    }
}
