//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JenisKendaraan
    {
        public JenisKendaraan()
        {
            this.Kendaraan = new HashSet<Kendaraan>();
        }
    
        public int ID { get; set; }
        public string Jenis { get; set; }
        public string Model { get; set; }
    
        public virtual ICollection<Kendaraan> Kendaraan { get; set; }
    }
}
