//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kendaraan
    {
        public int ID { get; set; }
        public int PemilikKendaraanID { get; set; }
        public int SamsatID { get; set; }
        public int MerekID { get; set; }
        public int JenisKendaraanID { get; set; }
        public int WarnaID { get; set; }
        public int WarnaTNKBID { get; set; }
        public int BahanBakarID { get; set; }
        public string NoPolisi { get; set; }
        public string Tipe { get; set; }
        public Nullable<int> TahunPembuatan { get; set; }
        public Nullable<int> TahunPerakitan { get; set; }
        public int IsiSilinder { get; set; }
        public string NoMesin { get; set; }
        public string NoRangka { get; set; }
        public string NoBPKB { get; set; }
    
        public virtual BahanBakar BahanBakar { get; set; }
        public virtual JenisKendaraan JenisKendaraan { get; set; }
        public virtual Merek Merek { get; set; }
        public virtual PemilikKendaraan PemilikKendaraan { get; set; }
        public virtual Samsat Samsat { get; set; }
        public virtual Tagihan Tagihan { get; set; }
        public virtual Warna Warna { get; set; }
        public virtual Warna Warna1 { get; set; }
    }
}
