//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PemilikKendaraan
    {
        public PemilikKendaraan()
        {
            this.Kendaraan = new HashSet<Kendaraan>();
        }
    
        public int ID { get; set; }
        public int NoKTP { get; set; }
        public Nullable<int> NoNPWP { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public Nullable<int> KodePos { get; set; }
    
        public virtual ICollection<Kendaraan> Kendaraan { get; set; }
    }
}
