//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provinsi
    {
        public Provinsi()
        {
            this.Kota = new HashSet<Kota>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
    
        public virtual ICollection<Kota> Kota { get; set; }
    }
}
