//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samsat
    {
        public Samsat()
        {
            this.Admin = new HashSet<Admin>();
            this.Kendaraan = new HashSet<Kendaraan>();
        }
    
        public int ID { get; set; }
        public int KotaID { get; set; }
        public string Nama { get; set; }
    
        public virtual ICollection<Admin> Admin { get; set; }
        public virtual ICollection<Kendaraan> Kendaraan { get; set; }
        public virtual Kota Kota { get; set; }
    }
}
